plugin: amazon.aws.aws_ec2

regions:
  - us-west-2

filters:
  instance-state-name: running
  

hostnames:
  - tag:Name
  - public-ip-address

keyed_groups:
  - key: tags.role
    prefix: role

compose:
  ansible_host: public_ip_address
